### ISSUE TITLE
lmd crashes with Panic: runtime error: index out of range

### ISSUE THREAD

**Issue by theseal** [sni/lmd#17]
Probably related to https://github.com/Icinga/icinga2/issues/5626 and https://github.com/sni/Thruk/issues/762

`lmd` v1.1.2 crashes immediately when trying to start it agains Icinga 2.7.1:

```
[2017-10-10 09:22:57][Error][main.go:515] Panic: runtime error: index out of range
[2017-10-10 09:22:57][Error][main.go:516] goroutine 27 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
main.logPanicExit()
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/main.go:516 +0xe0
panic(0x94d320, 0xc820010060)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
main.(*Peer).UpdateDeltaCommentsOrDowntimes(0xc8200fe4b0, 0xa07c60, 0x8, 0x0, 0x0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:723 +0x1cf8
main.(*Peer).UpdateDeltaTables(0xc8200fe4b0, 0xa01a80)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:497 +0x1c4
main.(*Peer).periodicUpdate(0xc8200fe4b0, 0xc823af1dcd, 0xc823af1dd0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:328 +0x4f4
main.(*Peer).updateLoop(0xc8200fe4b0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:273 +0x8aa
main.(*Peer).Start.func1(0xc8200fe4b0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:188 +0x46
created by main.(*Peer).Start
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:193 +0x2c8
```

**Comment by mickenordin** [comment]
I saw that you fixed https://github.com/sni/Thruk/issues/762 will you do the same for LMD?

**Comment by sni** [comment]
Can you try again? b58c83d0 and d94a252c might help.

**Comment by mickenordin** [comment]
Yes! It seems to work now :). Will you create a new release with these fixes?

**Comment by sni** [comment]
I sure will do. Currently hunting one last issue and then there will be a new release.

**Comment by sni** [comment]
Thanks for testing, closing this one then.
