### ISSUE TITLE
LMD panic

### ISSUE THREAD

**Issue by marcomusso** [sni/lmd#21]
Hi Sven, I just got my first panic on 1.1.5 since a long time:

```
[2018-02-26 12:56:05][Error][peer.go:2060] [Naemon] Panic: interface conversion: interface {} is nil, not []interface {}
[2018-02-26 12:56:05][Error][peer.go:2061] [Naemon] goroutine 35 [running]:
runtime/debug.Stack(0xc42015a9c0, 0x8eadab, 0xe)
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc4200a8c60)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:2061 +0x12f
panic(0x86a580, 0xc44735ac80)
        /usr/lib/golang/src/runtime/panic.go:491 +0x283
main.(*Peer).parseResult.func1(0xc46a831d66, 0x1c6, 0x87c09a, 0x4, 0x783d56, 0x0, 0x0)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:941 +0x186
github.com/buger/jsonparser.ArrayEach(0xc46a0ae010, 0x83e19a, 0xfffdf0, 0xc4657c7510, 0x0, 0x0, 0x0, 0x83e1aa, 0x389, 0x83aa00)
        /home/musso/src/go_workspace/src/github.com/buger/jsonparser/parser.go:898 +0x2e8
main.(*Peer).parseResult(0xc4200a8c60, 0xc4203ba000, 0xc446cbc0c0, 0xc458834000, 0x3153, 0x32aa, 0xb21a80, 0xc443f84188)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:939 +0x70b
main.(*Peer).query(0xc4200a8c60, 0xc4203ba000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:916 +0x8a6
main.(*Peer).Query(0xc4200a8c60, 0xc4203ba000, 0x2, 0x11, 0xc4657c7888, 0x2, 0x2)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:1005 +0x39
main.(*Peer).UpdateDeltaTableServices(0xc4200a8c60, 0xc43446bb00, 0x867, 0x0, 0x0)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:635 +0x289
main.(*Peer).UpdateDeltaTableFullScan(0xc4200a8c60, 0xc42018ad00, 0xc448419080, 0x40, 0x1, 0xc448419080, 0x40)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:720 +0xb08
main.(*Peer).UpdateDeltaTableServices(0xc4200a8c60, 0xc448419080, 0x40, 0x0, 0x0)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:623 +0x9f9
main.(*Peer).UpdateDeltaTables(0xc4200a8c60, 0x8e89b9)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:529 +0xb0f
main.(*Peer).periodicUpdate(0xc4200a8c60, 0xc4657c7e7e, 0xc4657c7e80)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:366 +0x370
main.(*Peer).updateLoop(0xc4200a8c60)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:298 +0x17b
main.(*Peer).Start.func1(0xc4200a8c60)
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:208 +0x59
created by main.(*Peer).Start
        /home/musso/src/go_workspace/src/github.com/sni/lmd/lmd/peer.go:205 +0x17f
[2018-02-26 12:56:05][Error][peer.go:2063] [Naemon] LastQuery:
[2018-02-26 12:56:05][Error][peer.go:2064] [Naemon] GET services
ResponseHeader: fixed16
OutputFormat: json
Columns: accept_passive_checks acknowledged acknowledgement_type active_checks_enabled check_options check_type checks_enabled comments current_attempt current_notification_number downtimes event_handler_enabled execution_time first_notification_delay flap_detection_enabled has_been_checked in_check_period in_notification_period is_executing is_flapping last_check last_hard_state last_hard_state_change last_notification last_state last_state_change last_time_critical last_time_warning last_time_ok last_time_unknown latency long_plugin_output low_flap_threshold modified_attributes modified_attributes_list next_check next_notification notifications_enabled obsess_over_service percent_state_change perf_data plugin_output process_performance_data scheduled_downtime_depth state state_type staleness host_name description
Filter: last_check >= 1519649758
Filter: is_executing = 1
Or: 2
Filter: last_check = 1519649736
Filter: last_check = 1519649760
Filter: last_check = 1519649747
Filter: last_check = 1519649690
Filter: last_check = 1519649738
Filter: last_check = 1519649712
Filter: last_check = 1519649709
Filter: last_check = 1519649664
Filter: last_check = 1519649741
Filter: last_check = 1519649757
Filter: last_check = 1519649734
Filter: last_check = 1519649748
Filter: last_check = 1519649718
Filter: last_check = 1519649737
Filter: last_check = 1519649758
Filter: last_check = 1519649660
Filter: last_check = 1519649739
Filter: last_check = 1519649759
Filter: last_check = 1519649745
Filter: last_check = 1519649725
Filter: last_check = 1519649730
Filter: last_check = 1519649729
Filter: last_check = 1519649754
Filter: last_check = 1519649673
Filter: last_check = 1519649681
Filter: last_check = 1519649716
Filter: last_check = 1519649750
Filter: last_check = 1519649722
Filter: last_check = 1519649733
Filter: last_check = 1519649691
Filter: last_check = 1519649657
Filter: last_check = 1519649710
Filter: last_check = 1519649662
Filter: last_check = 1519649727
Filter: last_check = 1519649756
Filter: last_check = 1519649724
Filter: last_check = 1519649706
Filter: last_check = 1519649682
Filter: last_check = 1519649753
Filter: last_check = 1519649665
Filter: last_check = 1519649676
Filter: last_check = 1519649696
Filter: last_check = 1519649720
Filter: last_check = 1519649695
Filter: last_check = 1519649746
Filter: last_check = 1519649755
Filter: last_check = 1519649732
Filter: last_check = 1519649719
Filter: last_check = 1519649671
Filter: last_check = 1519649717
Filter: last_check = 1519649675
Filter: last_check = 1519649752
Filter: last_check = 1519649714
Filter: last_check = 1519649698
Filter: last_check = 1519649721
Filter: last_check = 1519649692
Filter: last_check = 1519649728
Filter: last_check = 1519649735
Filter: last_check = 1519649674
Filter: last_check = 1519649749
Filter: last_check = 1519649742
Filter: last_check = 1519649726
Filter: last_check = 1519649731
Filter: last_check = 1519649751
Filter: last_check = 1519649743
Or: 66

[2018-02-26 12:56:05][Error][peer.go:2065] [Naemon] LastResponse:
```
Followed by a huge array of services...

Any chance that this is fixed in 1.2.0?

**Comment by sni** [comment]
Not in the 1.2.0 but it sounds like a issue with garbled/incomplete json results which should be fixed in HEAD with https://github.com/sni/lmd/commit/cd993abf5ea1299e52ef20ea2a760961d895c4f9

**Comment by marcomusso** [comment]
Ok thx!
