### ISSUE TITLE
LMD Panic interface {} is bool, not float64

### ISSUE THREAD

**Issue by Torsteng5** [sni/lmd#39]
Hi,

I installed Thruk, Icinga2 and LMD on fresh Ubuntu 1804 and get this Error at every Request:
```
[2018-07-27 19:37:26][Error][peer.go:2462] [Icinga2] LastResponse:
[2018-07-27 19:37:26][Error][peer.go:2463] [Icinga2] [[1532713039.0,0.0,false,1.0,1.0], [1532713033.0,0.0,false,1.0,1.0], [1532713032.0,0.0,false,1.0,1.0], [1532712760.0,0.0,false,1.0,1.0], [1532713006.0,0.0,false,1.0,1.0], [1532712949.0,0.0,false,1.0,1.0], [1532712979.0,0.0,false,1.0,1.0], [1532713034.0,0.0,false,1.0,1.0], [1532712980.0,0.0,false,1.0,1.0], [1532713003.0,0.0,false,1.0,1.0], [1532713018.0,0.0,false,1.0,1.0], [1532712986.0,0.0,false,1.0,1.0], [1532712981.0,0.0,false,1.0,1.0], [1532713033.0,0.0,false,1.0,1.0], [1532713023.0,0.0,false,1.0,1.0], [1532713037.0,0.0,false,1.0,1.0], [1532713018.0,0.0,false,1.0,1.0], [1532713039.0,0.0,false,1.0,1.0], [1532712986.0,0.0,false,1.0,1.0], [1532713030.0,0.0,false,1.0,1.0], [1532712986.0,0.0,false,1.0,1.0], [1532712944.0,0.0,false,1.0,1.0], [1532712948.0,0.0,false,1.0,1.0], [1532713042.0,0.0,false,1.0,1.0], [1532712996.0,0.0,false,1.0,1.0], [1532712969.0,0.0,false,1.0,1.0], [1532712951.0,0.0,false,1.0,0.0], [1532713003.0,0.0,false,1.0,1.0], [1532713042.0,0.0,false,1.0,1.0]]
[2018-07-27 19:37:58][Warn][listener.go:218] removing stale socket: /var/cache/thruk/lmd/live.sock
[2018-07-27 19:37:58][Warn][listener.go:218] removing stale socket: /var/cache/thruk/lmd/live.sock
[2018-07-27 19:38:03][Error][peer.go:2457] [Icinga2] Panic: interface conversion: interface {} is bool, not float64
[2018-07-27 19:38:03][Error][peer.go:2458] [Icinga2] goroutine 36 [running]:
runtime/debug.Stack(0xc42019e090, 0x90f0eb, 0xe)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc4202260c0)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2458 +0x12f
panic(0x8861a0, 0xc420450f00)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
main.(*Peer).getMissingTimestamps(0xc4202260c0, 0xc42013cc30, 0xc420320780, 0xc42005fa78, 0xc420572e10, 0x5, 0x5, 0xc420226000, 0x5b5b5878, 0x7600000001)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:894 +0x67e
main.(*Peer).UpdateDeltaTableFullScan(0xc4202260c0, 0xc42013cc30, 0xc4204a9dc0, 0x40, 0x1, 0xc4204a9dc0, 0x40)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:848 +0x417
main.(*Peer).UpdateDeltaTableHosts(0xc4202260c0, 0xc4204a9dc0, 0x40, 0x0, 0x0)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:712 +0x86d
main.(*Peer).UpdateDeltaTables(0xc4202260c0, 0x90cbd7)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:665 +0xac4
main.(*Peer).periodicUpdate(0xc4202260c0, 0xc42005fe76, 0xc42005fe78)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:394 +0x370
main.(*Peer).updateLoop(0xc4202260c0)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:325 +0x2da
main.(*Peer).Start.func1(0xc4202260c0)
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:226 +0x59
created by main.(*Peer).Start
	/opt/local/go/src/github.com/sni/lmd/lmd/peer.go:223 +0x17f
[2018-07-27 19:38:03][Error][peer.go:2460] [Icinga2] LastQuery:
[2018-07-27 19:38:03][Error][peer.go:2461] [Icinga2] GET hosts
ResponseHeader: fixed16
OutputFormat: json
Columns: last_check scheduled_downtime_depth acknowledged active_checks_enabled notifications_enabled
```

Thruk 2.22
Icinga r2.9.0-1
LMD 1.3.3

/var/cache/thruk/lmd/lmd.ini:
```
Listen = ['/var/cache/thruk/lmd/live.sock']

LogFile = '/var/cache/thruk/lmd/lmd.log'

LogLevel = 'Warn'

[[Connections]]
name    = 'Icinga2'
id      = '0ac2d'
source  = ['/var/run/icinga2/cmd/livestatus']
```

/etc/thruk/thruk_local.d/lmd.conf:
```
use_lmd_core=1
lmd_core_bin=/opt/local/go/bin/lmd
lmd_core_config = /var/cache/thruk/lmd/lmd.ini
```

/etc/thruk/thruk_local.conf:
```
<Component Thruk::Backend>
    <peer>
        name    = Icinga2
        id      = 0ac2d
        type    = livestatus
        <options>
            peer          = /var/run/icinga2/cmd/livestatus
        </options>
    </peer>
</Component>
```

**Comment by sni** [comment]
should be better now, thanks for your report.

**Comment by Ago1984** [comment]
Hi,

I've upgraded my thruk in 2.30 on debian base with icinga2 and lmd and i've got the same error as in this issue.

`[2019-05-16 16:01:40][Warn][listener.go:218] removing stale socket: /var/cache/thruk/lmd/live.sock
[2019-05-16 16:01:46][Error][peer.go:2381] [Icinga2] Panic: interface conversion: interface is bool, not float64
[2019-05-16 16:01:46][Error][peer.go:2382] [Icinga2] goroutine 53 [running]:
runtime/debug.Stack(0xc420075a70, 0x8d40ed, 0xe)
        /usr/lib/go-1.7/src/runtime/debug/stack.go:24 +0x79
main.logPanicExitPeer(0xc4200ee240)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2382 +0x130
panic(0x859c00, 0xc4208414c0)
        /usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
main.(*Peer).getMissingTimestamps(0xc4200ee240, 0xc4201bc410, 0xc42000e780, 0xc420045908, 0xc421286180, 0x5, 0x5, 0x0, 0xc420256400, 0x0)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:891 +0x1d6
main.(*Peer).UpdateDeltaTableFullScan(0xc4200ee240, 0xc4201bc410, 0xc421001100, 0x40, 0x1, 0xc421001100, 0x40)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:845 +0x3d7
main.(*Peer).UpdateDeltaTableHosts(0xc4200ee240, 0xc421001100, 0x40, 0x0, 0x0)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:709 +0x9d0
main.(*Peer).UpdateDeltaTables(0xc4200ee240, 0x8d1858)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:662 +0xb5b
main.(*Peer).periodicUpdate(0xc4200ee240, 0xc420045dbb, 0xc420045dc0)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:391 +0x581
main.(*Peer).updateLoop(0xc4200ee240)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:322 +0x256
main.(*Peer).Start.func1(0xc4200ee240)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:223 +0x59
created by main.(*Peer).Start
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:228 +0x1b9
[2019-05-16 16:01:46][Error][peer.go:2384] [Icinga2] LastQuery:
[2019-05-16 16:01:46][Error][peer.go:2385] [Icinga2] GET hosts
ResponseHeader: fixed16
OutputFormat: json
Columns: last_check scheduled_downtime_depth acknowledged active_checks_enabled notifications_enabled
`
Thruk 2.30
Icinga r2.10.4-1
LMD 1.3.0

/var/cache/thruk/lmd/lmd.ini:

Listen = ['/var/cache/thruk/lmd/live.sock']
LogFile = '/var/cache/thruk/lmd/lmd.log'
LogLevel = 'Warn'
[[Connections]]
name    = 'Icinga2'
id      = '7265e'
source  = ['127.0.0.1:6558']

/etc/thruk/thruk_local.d/lmd.conf:

use_lmd_core=1
lmd_core_bin=/opt/local/go/bin/lmd

/etc/thruk/thruk_local.conf:

<Component Thruk::Backend>
    <peer>
        name    = Icinga2
        id      = 7265e
        type    = livestatus
        <options>
            peer          = 127.0.0.1:6558
        </options>
    </peer>
</Component>

**Comment by sni** [comment]
please try the latest lmd 1.5.0

**Comment by Ago1984** [comment]
with lmd 1.5.0 i've got 

`[2019-05-16 16:20:03.388][Warn][listener.go:241] removing stale socket: /var/cache/thruk/lmd/live.sock
[2019-05-16 16:20:04.109][Error][peer.go:2519] [Icinga2] Panic: interface conversion: interface {} is nil, not string
[2019-05-16 16:20:04.109][Error][peer.go:2520] [Icinga2] Version: 1.5.0 (Build: )
[2019-05-16 16:20:04.109][Error][peer.go:2521] [Icinga2] goroutine 37 [running]:
runtime/debug.Stack(0xc00013a480, 0x952c98, 0x10)
        /usr/lib/go-1.11/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc000286000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2521 +0x21a
panic(0x8cad80, 0xc0007e2c30)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
main.(*Peer).buildDowntimeCommentsCache(0xc000286000, 0x94e109, 0x8, 0x29)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2702 +0x4ce
main.(*Peer).RebuildCommentsCache(0xc000286000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2676 +0x44
main.(*Peer).InitAllTables(0xc000286000, 0xc000132a20)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:701 +0xecc
main.(*Peer).updateLoop(0xc000286000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:304 +0x5ac
main.(*Peer).Start.func1(0xc000286000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:234 +0x59
created by main.(*Peer).Start
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:231 +0x178
[2019-05-16 16:20:04.109][Error][peer.go:2523] [Icinga2] LastQuery:
[2019-05-16 16:20:04.109][Error][peer.go:2524] [Icinga2] GET comments
ResponseHeader: fixed16
OutputFormat: json
Columns: author comment entry_time entry_type expires expire_time id is_service persistent source type host_name service_description
KeepAlive: on`

**Comment by sni** [comment]
ok, i am reworking internal storage right now and this includes validating input as well, so i will consider this issue...

**Comment by Ago1984** [comment]
thx, i'm trying it on fresh install.

**Comment by Ago1984** [comment]
same with fresh install and the update to thruk 2.30-2 return the same error.
```
[2019-05-20 14:50:03.119][Warn][listener.go:241] removing stale socket: /var/cache/thruk/lmd/live.sock
[2019-05-20 14:50:03.851][Error][peer.go:2519] [Icinga2] Panic: interface conversion: interface {} is nil, not string
[2019-05-20 14:50:03.851][Error][peer.go:2520] [Icinga2] Version: 1.5.0 (Build: )
[2019-05-20 14:50:03.851][Error][peer.go:2521] [Icinga2] goroutine 20 [running]:
runtime/debug.Stack(0xc0001820f0, 0x952c98, 0x10)
        /usr/lib/go-1.11/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc000236000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2521 +0x21a
panic(0x8cad80, 0xc000ed4c00)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
main.(*Peer).buildDowntimeCommentsCache(0xc000236000, 0x94e109, 0x8, 0x29)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2702 +0x4ce
main.(*Peer).RebuildCommentsCache(0xc000236000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:2676 +0x44
main.(*Peer).InitAllTables(0xc000236000, 0xc0001837a0)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:701 +0xecc
main.(*Peer).updateLoop(0xc000236000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:304 +0x5ac
main.(*Peer).Start.func1(0xc000236000)
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:234 +0x59
created by main.(*Peer).Start
        /opt/local/go/src/github.com/sni/lmd/lmd/peer.go:231 +0x178
[2019-05-20 14:50:03.851][Error][peer.go:2523] [Icinga2] LastQuery:
[2019-05-20 14:50:03.851][Error][peer.go:2524] [Icinga2] GET comments
ResponseHeader: fixed16
OutputFormat: json
Columns: author comment entry_time entry_type expires expire_time id is_service persistent source type host_name service_description
KeepAlive: on

[2019-05-20 14:50:03.851][Error][peer.go:2525] [Icinga2] LastResponse:
[2019-05-20 14:50:03.851][Error][peer.go:2526] [Icinga2]
```

**Comment by sni** [comment]
could you retry with latest HEAD, such type conversion panics should not happen anymore.

**Comment by Ago1984** [comment]
same results, we've removed lmd.

**Comment by sni** [comment]
which version, which line?

**Comment by jsofronis** [comment]
Well in my case this error in lmd.log happend after i acknowledged a hosts's problem with a comment "Einai proswrina Down"

omd version 2.90-labs-edition
lmd - version 1.3.7 (Build: 2.90-labs-edition-v1.3.7)

`2019-12-22 14:35:07][Error][peer.go:2698] [noc] LastResponse:
[2019-12-22 14:35:07][Error][peer.go:2699] [noc] [["srvadmin","Einai proswrina Down",1576963609.0,4.0,false,0.0,1.0,0.0,1.0,1.0,1.0,"web2.noc",null]]
[2019-12-22 14:35:41][Warn][listener.go:246] removing stale socket: /omd/sites/noc/tmp/thruk/lmd/live.sock
[2019-12-22 14:35:46][Error][peer.go:2693] [noc] Panic: interface conversion: interface {} is nil, not string
[2019-12-22 14:35:46][Error][peer.go:2694] [noc] goroutine 8 [running]:
runtime/debug.Stack(0xc00009d770, 0x954ad4, 0xe)
        /opt/projects/omd/packages/go-1.11/go-1.11.4/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc00017e180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2694 +0x125
panic(0x8cbc80, 0xc000264600)
        /opt/projects/omd/packages/go-1.11/go-1.11.4/src/runtime/panic.go:513 +0x1b9
main.(*Peer).expandCrossServiceReferences(0xc00017e180, 0xc00012cff0, 0xc0000dfc40, 0xc0000dfce8, 0xc0001de180, 0x0, 0x0, 0x0)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2818 +0x867
main.(*Peer).initilizeReferences(0xc00017e180, 0xc00012cff0, 0xc0000dfce8, 0xc0002645d0, 0x0, 0x0)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2756 +0x28f
main.(*Peer).CreateObjectByType(0xc00017e180, 0xc00012cff0, 0x95138a, 0x8)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:1532 +0x2c1
main.(*Peer).InitAllTables(0xc00017e180, 0xc00013f080)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:663 +0x915
main.(*Peer).updateLoop(0xc00017e180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:314 +0x596
main.(*Peer).Start.func1(0xc00017e180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:244 +0x59
created by main.(*Peer).Start
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:241 +0x178
[2019-12-22 14:35:46][Error][peer.go:2696] [noc] LastQuery:
[2019-12-22 14:35:46][Error][peer.go:2697] [noc] GET comments
ResponseHeader: fixed16
OutputFormat: json
Columns: author comment entry_time entry_type expires expire_time id is_service persistent source type host_name service_description`
