### ISSUE TITLE
] Panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by jsofronis** [sni/lmd#91]
lmd - version 1.3.7 (Build: 2.90-labs-edition-v1.3.7)
OMD - Open Monitoring Distribution Version 2.90-labs-edition

The logs below started when i acknowledged a host problem with the commend "Einai proswrina Down" with no expiration time. 
Any ideas on what is gong on with the LMD ?

```
[2019-12-23 00:41:07][Error][peer.go:2693] [noc] Panic: interface conversion: interface {} is nil, not string
[2019-12-23 00:41:07][Error][peer.go:2694] [noc] goroutine 6 [running]:
runtime/debug.Stack(0xc0001a6030, 0x954ad4, 0xe)
        /opt/projects/omd/packages/go-1.11/go-1.11.4/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc00023c180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2694 +0x125
panic(0x8cbc80, 0xc00052a240)
        /opt/projects/omd/packages/go-1.11/go-1.11.4/src/runtime/panic.go:513 +0x1b9
main.(*Peer).expandCrossServiceReferences(0xc00023c180, 0xc0001aed20, 0xc000bafc40, 0xc000bafce8, 0xc000205c80, 0x0, 0x0, 0x0)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2818 +0x867
main.(*Peer).initilizeReferences(0xc00023c180, 0xc0001aed20, 0xc000bafce8, 0xc00052a210, 0x0, 0x0)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:2756 +0x28f
main.(*Peer).CreateObjectByType(0xc00023c180, 0xc0001aed20, 0x95138a, 0x8)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:1532 +0x2c1
main.(*Peer).InitAllTables(0xc00023c180, 0xc0001a76e0)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:663 +0x915
main.(*Peer).updateLoop(0xc00023c180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:314 +0x596
main.(*Peer).Start.func1(0xc00023c180)
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:244 +0x59
created by main.(*Peer).Start
        /opt/projects/omd/packages/lmd/go/src/github.com/sni/lmd/lmd/peer.go:241 +0x178
[2019-12-23 00:41:07][Error][peer.go:2696] [noc] LastQuery:
[2019-12-23 00:41:07][Error][peer.go:2697] [noc] GET comments
ResponseHeader: fixed16
OutputFormat: json
Columns: author comment entry_time entry_type expires expire_time id is_service persistent source type host_name service_description

[2019-12-23 00:41:07][Error][peer.go:2698] [noc] LastResponse:
[2019-12-23 00:41:07][Error][peer.go:2699] [noc] [["srvadmin","Einai proswrina Down",1576963609.0,4.0,false,0.0,1.0,0.0,1.0,1.0,1.0,"web2.noc",null]]

```

**Comment by jsofronis** [comment]
Finally, everything went ok when i turned this host on again !

**Comment by sni** [comment]
I assume this has been fixed long time ago. You could try to update either OMD or if thats not possible, then only LMD.
